# [general]
import = ["~/.config/alacritty/catppuccin-mocha.toml"]

[cursor.style]
shape = "Block"

[env]
TERM = "xterm-256color"

[font]
size = 13

[font.normal]
family = "JetBrainsMono Nerd Font"

[mouse]
hide_when_typing = true

[[keyboard.bindings]]
key = "F11"
action = "ToggleFullscreen"

[window]
decorations = "none"
dynamic_padding = false

[window.padding]
x = 0
y = 0
