theme = "gruvbox_dark_hard"

[editor]
line-number = "relative"

[keys.normal]
esc = ["collapse_selection", "keep_primary_selection"]

[keys.normal.space.e]
f = [
  ':sh rm -f /tmp/unique-file',
  ':insert-output yazi "%{buffer_name}" --chooser-file=/tmp/unique-file',
  ':sh printf "\x1b[?1049h\x1b[?2004h" > /dev/tty',
  ':open %sh{cat /tmp/unique-file}',
  ':redraw',
]
d = [
  ':sh rm -f /tmp/unique-file',
  ':insert-output yazi --chooser-file=/tmp/unique-file',
  ':sh printf "\x1b[?1049h\x1b[?2004h" > /dev/tty',
  ':open %sh{cat /tmp/unique-file}',
  ':redraw',
]

[editor.cursor-shape]
insert = "bar"
